# -*- mode: python ; coding: utf-8 -*-
import os
from PyInstaller.utils.hooks import collect_submodules
from PyInstaller.utils.hooks import collect_all

# Windows exe icon. Generated by installer/make_assets.py (git-ignored), so
# fall back to no icon if it hasn't been built yet.
_icon = os.path.join('installer', 'assets', 'installer.ico')
app_icon = _icon if os.path.exists(_icon) else None

datas = [('src/ps5_image_forge/webui', 'ps5_image_forge/webui'), ('src/ps5_image_forge/payload_catalog.json', 'ps5_image_forge'), ('vendor/payloads', 'ps5_image_forge/bundled_payloads'), ('vendor/ufs2tool', 'ufs2tool')]
binaries = []
hiddenimports = []
hiddenimports += collect_submodules('mkpfs')
tmp_ret = collect_all('webview')
datas += tmp_ret[0]; binaries += tmp_ret[1]; hiddenimports += tmp_ret[2]


a = Analysis(
    ['entry.py'],
    pathex=[],
    binaries=binaries,
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='PS5-Image-Forge',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=app_icon,
)
